/**
 * List of categories defined by the sites.
 */
export const categories: string[] = [
  'rating',
  'spoiler',
  'origin',
  'oc',
  'error',
  'character',
  'content-official',
  'content-fanmade',
  'species',
  'body-type',
];

/**
 * List of tags which marked by the site as blacklisted. These tags are blocked from being added by the tag editor and
 * should usually just be removed automatically.
 */
export const tagsBlacklist: string[] = (__CURRENT_SITE__ === 'furbooru' ? [
  "anthro art",
  "anthro artist",
  "anthro cute",
  "anthro furry",
  "anthro nsfw",
  "anthro oc",
  "anthroart",
  "anthroartist",
  "anthrofurry",
  "anthronsfw",
  "anthrooc",
  "art",
  "artist",
  "artwork",
  "cringe",
  "cringeworthy",
  "cute art",
  "cute artwork",
  "cute furry",
  "downvotes galore",
  "drama in comments",
  "drama in the comments",
  "fandom",
  "furries",
  "furry anthro",
  "furry art",
  "furry artist",
  "furry artwork",
  "furry character",
  "furry community",
  "furry cute",
  "furry fandom",
  "furry nsfw",
  "furry oc",
  "furryanthro",
  "furryart",
  "furryartist",
  "furryartwork",
  "furrynsfw",
  "furryoc",
  "image",
  "no tag",
  "not tagged",
  "notag",
  "notags",
  "nsfw anthro",
  "nsfw art",
  "nsfw artist",
  "nsfw artwork",
  "nsfw",
  "nsfwanthro",
  "nsfwart",
  "nsfwartist",
  "nsfwartwork",
  "paywall",
  "rcf community",
  "sfw",
  "solo oc",
  "tag me",
  "tag needed",
  "tag your shit",
  "tagme",
  "upvotes galore",
  "wall of faves"
] : [
  "tagme",
  "tag me",
  "not tagged",
  "no tag",
  "notag",
  "notags",
  "upvotes galore",
  "downvotes galore",
  "wall of faves",
  "drama in the comments",
  "drama in comments",
  "tag needed",
  "paywall",
  "cringeworthy",
  "solo oc",
  "tag your shit"
]);
